# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "External operators with FEniCSx"
author: Andrey Latyshev, Jack S. Hale
copyright: "2023"

execute:
  execute_notebooks: force
  timeout: 200
# Information about where the book exists on the web
repository:
  url: https://github.com/a-latyshev/dolfinx-external-operator/  # Online location of your book
  branch: main # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"

html:
  use_issues_button: true
  use_repository_button: true
  favicon: "favicon.ico"

bibtex_bibfiles:
  - references.bib

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify
    - html_image

sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.viewcode"

  config:
    html_theme_options:
      navigation_with_keys: false
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py
