# Simple workflow for deploying static content to GitHub Pages
name: Build documentation

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "publishing"
  pull_request:
    branches:
      - "main"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/dolfinx:nightly
    
    env:
      PYVISTA_TRAME_SERVER_PROXY_PREFIX: "/proxy/"
      PYVISTA_TRAME_SERVER_PROXY_ENABLED: "True"
      PYVISTA_OFF_SCREEN: false
      PYVISTA_JUPYTER_BACKEND: "html"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install package
        run: |
          apt-get update && apt-get install -y libxrender1 xvfb
          pip install --no-build-isolation --break-system-packages --no-cache-dir '.[ci]' 

      - name: Run tests
        run: |
          python3 -m pytest tests/

      - name: ruff check and format
        run: |
          ruff check .
          ruff format --check .

      - name: Build book
        run: jupyter book build docs/
      
      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v3
        with:
          name: webpage
          path: docs/_build/html
          if-no-files-found: error
